# Generated by Django 4.1.4 on 2023-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("Tiltle", models.CharField(max_length=20)),
                ("Description", models.TextField()),
                ("Createion", models.DateTimeField(auto_now=True)),
                ("Due_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "open"),
                            ("working", "working"),
                            ("done", "done"),
                            ("overdue", "overdue"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
