# Generated by Django 4.1.4 on 2023-12-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="Tiltle",
            new_name="Title",
        ),
        migrations.AddField(
            model_name="todo",
            name="tags",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="todo",
            name="Due_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "open"),
                    ("working", "working"),
                    ("done", "done"),
                    ("overdue", "overdue"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
