# Generated by Django 4.1.4 on 2023-12-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_rename_tiltle_todo_title_todo_tags_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="Due_date",
            field=models.DateTimeField(),
        ),
    ]
