# Generated by Django 4.1.4 on 2023-12-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_todo_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="Due_date",
            field=models.DateField(),
        ),
    ]
